version: '3.8'

services:
  app1:
    build:
      context: ./app1
      dockerfile: Dockerfile
    ports:
      - "8081:80"

  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    ports:
      - "8082:80"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
